### ISSUE TITLE
Undocumented /home/$USER/.duck6.conf created by script

### ISSUE THREAD

**Issue by RottenRonnie** [gtwy/IPv6forDuckDNS#10]
Situation:
I installed this service using an incorrect domain, and wanted to update the one in use, but could not determine why the setup script could not be run a second time to correct the domain error. 

Solution:
The script writes a file in the user home directory /home/$USER/.duck6.conf with the supplied domain name and token. I was able to manually edit this file to change the domain name to correct the error. 

I feel that the Read.ME file should mention the creation of the file, and the script could confirm the write operation as well, such as 
"Configuration file successfully written to .duck6.conf" or similar. 

![image](https://github.com/gtwy/IPv6forDuckDNS/assets/10812745/cf4f64fb-781d-4f33-9531-eba67c620a0d)

**Comment by gtwy** [comment]
Sure that's not a bad idea. I'll add it.

Are people still using this script? I find it odd that DuckDNS is still not supporting ipv6. I thought that AWS supported ipv6 now.

**Comment by RottenRonnie** [comment]
I used to have a traditional IPV4 address accessible to ssh via TCP, but moved in to a home that uses Carrier Grade Network Address Translation or CGNAT. I've needed to use IPV6 now and products such as WireGuard, Cloudflare, the older ngrok etc. 

Thank you! 

Duckdns shows the IPV6 but only after using your script to push the details. 
![image](https://github.com/gtwy/IPv6forDuckDNS/assets/10812745/855d1ed7-b4e3-49ce-9117-72f0e21a6b7f)
