### ISSUE TITLE
Does this still work?

### ISSUE THREAD

**Issue by Mithrandir2k18** [gtwy/IPv6forDuckDNS#4]
I have been trying to replicate this, but no luck yet. Curl returns OK, but the website doesn't show an IPv6 entry and gives an error when hitting the update button.

A question about this was also posted [here](https://superuser.com/q/1634497) but that didn't get a working answer yet it seems.

**Comment by gtwy** [comment]
I've had static addressing for the last few years, so I'm not actually using the script. However, it appears that everything is still working ok with website to tell people an IPv6 address. Did DuckDNS change their URL structure for submitting an IPv6 address by any chance?

Just out of curiosity, what distro are you using?

**Comment by Mithrandir2k18** [comment]
I am using it on headless-raspian on a raspberrypi3, so a debian/ubuntu-ish flavor.

I couldn't really find any documentation by DuckDNS on how to publish IPv6.

**Comment by gtwy** [comment]
I'm not having any problems here. I just ran the script and it connected fine.

For troubleshooting purposes, Change [this line](https://github.com/gtwy/IPv6forDuckDNS/blob/915dc900d311d4c8389db89b1f5c31d904ccdc22/autoconf-duckdns6.sh#L46) from "curl -s" to "echo"

`curl -s "https://www.duckdns.org/update?domains=$duckdomain&token=$ducktoken&ip=$ipv4addr&ipv6=$ipv6addr"`
to this
`echo "https://www.duckdns.org/update?domains=$duckdomain&token=$ducktoken&ip=$ipv4addr&ipv6=$ipv6addr"`

If there appears to be a problem, such as a variable not coming through or syntax error, let me know. On the other hand, if it looks totally fine, try to copy the URL and paste it into a web browser to see if it properly updates. I'll also need to see the result, but I understand that you may not want to publicly broadcast your IPv4 and IPv6 address on GitHub. (Maybe use a pastebin service that expires after a day?)

Every couple years someone with a raspberry pi opens this same ticket.

**Comment by gtwy** [comment]
Be aware that you have to change that line in the duckdns6.sh file in your home directory as opposed to the autoconf-duckdns6.sh script.

**Comment by gtwy** [comment]
I've updated the code to add more verbose messages. Please clone and run the newest version of this script and let me know if you are still having a problem. I am going to close the ticket for now, but will reopen it if it turns out that the verbose logging does not solve the issue.
