### ISSUE TITLE
Is there a way to only update the IPv6

### ISSUE THREAD

**Issue by BUGBEAR7** [gtwy/IPv6forDuckDNS#6]
Hello 

First of all thanks for the script it works well , but I have a small issue with IPv4 . My ISP have CG-NAT which blocks all port on IPv4 so when the scripts runs it also update my IPv4 to duckdns which is causing me some issue accessing it over internet . If I remove the IPv4 manually in duckdns IPv6 works fine .

So my question is , is there any way for the script not to update the IPv4 and just update the IPv6.

Thanks

**Comment by gtwy** [comment]
If I recall correctly, and it's been a few years, but I'm pretty sure the only reason I even included the IPv4 part is that their URL syntax required it. You could try taking the URL generated for your cron job and remove the IPv4 value. This would not be something my script would ever support, but you could modify it on your end.

**Comment by BUGBEAR7** [comment]
Hello 
Thanks for the response , I tried testing it by removing the IPv4 part but it does not seem to work. I have found an addon on Homeassistant community as I am using HA with that addon I am only able to update the IPv6 and that works fine.
