### ISSUE TITLE
Issue getting the ipv6 locally: update grep filters?

### ISSUE THREAD

**Issue by FernandoMarques-Santos** [gtwy/IPv6forDuckDNS#8]
First, thanks for providing your code. I've been using it for some years now.

I'm having an issue extracting the right ipv6 address. The problem started when for some reason I have a temporary address that the script pulls instead of the right one:

![image](https://user-images.githubusercontent.com/33721644/235376507-17f88225-a7bd-442f-8aa5-fce99aed9b05.png)

I see that we already have filters for fd00 and fe80. May I suggest filtering out any addresses that start with f? That should do the trick

**Comment by gtwy** [comment]
I can make this adjustment before the end of the week, but I'm traveling at the moment. You may want to just edit the script on your side in the meantime to block it until then. I'll update this thread when I've had a chance to update it.

(PS: If someone else wants to resolve, I will approve the pull request.)

**Comment by gtwy** [comment]
Looks like just eliminating the "00" from "grep -v '^fd00'" in this line would fix it

https://github.com/gtwy/IPv6forDuckDNS/blob/master/autoconf-duckdns6.sh#L15
